// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package store

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const createChunk = `-- name: CreateChunk :one
INSERT INTO chunks (document_id, chunk_index, content, content_length)
VALUES ($1, $2, $3, $4)
RETURNING id, document_id, chunk_index, content, content_length, embedding, created_at
`

type CreateChunkParams struct {
	DocumentID    int64  `json:"document_id"`
	ChunkIndex    int32  `json:"chunk_index"`
	Content       string `json:"content"`
	ContentLength int32  `json:"content_length"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, createChunk,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.ContentLength,
	)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ChunkIndex,
		&i.Content,
		&i.ContentLength,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const listChunksByDocument = `-- name: ListChunksByDocument :many
SELECT id, document_id, chunk_index, content, content_length, embedding, created_at
FROM chunks
WHERE document_id = $1
ORDER BY chunk_index ASC
`

func (q *Queries) ListChunksByDocument(ctx context.Context, documentID int64) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, listChunksByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.ContentLength,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChunks = `-- name: SearchChunks :many
SELECT
    chunks.id,
    chunks.document_id,
    documents.name AS document_name,
    chunks.chunk_index,
    chunks.content,
    chunks.content_length,
    (1 - (chunks.embedding <=> $2::vector))::double precision AS score
FROM chunks
JOIN documents ON documents.id = chunks.document_id
WHERE chunks.embedding IS NOT NULL
ORDER BY chunks.embedding <=> $2::vector
LIMIT $1
`

type SearchChunksParams struct {
	Limit          int32           `json:"limit"`
	QueryEmbedding pgvector.Vector `json:"query_embedding"`
}

type SearchChunksRow struct {
	ID            int64   `json:"id"`
	DocumentID    int64   `json:"document_id"`
	DocumentName  string  `json:"document_name"`
	ChunkIndex    int32   `json:"chunk_index"`
	Content       string  `json:"content"`
	ContentLength int32   `json:"content_length"`
	Score         float64 `json:"score"`
}

func (q *Queries) SearchChunks(ctx context.Context, arg SearchChunksParams) ([]SearchChunksRow, error) {
	rows, err := q.db.Query(ctx, searchChunks, arg.Limit, arg.QueryEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksRow
	for rows.Next() {
		var i SearchChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.DocumentName,
			&i.ChunkIndex,
			&i.Content,
			&i.ContentLength,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChunkEmbedding = `-- name: UpdateChunkEmbedding :exec
UPDATE chunks
SET embedding = $2
WHERE id = $1
`

type UpdateChunkEmbeddingParams struct {
	ID        int64           `json:"id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateChunkEmbedding(ctx context.Context, arg UpdateChunkEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateChunkEmbedding, arg.ID, arg.Embedding)
	return err
}
