// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (name, type, size, status, raw_text, error_message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, size, status, raw_text, error_message, created_at, updated_at
`

type CreateDocumentParams struct {
	Name         string      `json:"name"`
	Type         string      `json:"type"`
	Size         int64       `json:"size"`
	Status       string      `json:"status"`
	RawText      pgtype.Text `json:"raw_text"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Name,
		arg.Type,
		arg.Size,
		arg.Status,
		arg.RawText,
		arg.ErrorMessage,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Size,
		&i.Status,
		&i.RawText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, name, type, size, status, raw_text, error_message, created_at, updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Size,
		&i.Status,
		&i.RawText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, name, type, size, status, raw_text, error_message, created_at, updated_at
FROM documents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Size,
			&i.Status,
			&i.RawText,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2,
    error_message = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, size, status, raw_text, error_message, created_at, updated_at
`

type UpdateDocumentStatusParams struct {
	ID           int64       `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Size,
		&i.Status,
		&i.RawText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
