// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID            int64              `json:"id"`
	DocumentID    int64              `json:"document_id"`
	ChunkIndex    int32              `json:"chunk_index"`
	Content       string             `json:"content"`
	ContentLength int32              `json:"content_length"`
	Embedding     pgvector.Vector    `json:"embedding"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	Size         int64              `json:"size"`
	Status       string             `json:"status"`
	RawText      pgtype.Text        `json:"raw_text"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EvalReport struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	ConfigSnapshot []byte             `json:"config_snapshot"`
	TotalCases     int32              `json:"total_cases"`
	PassedCases    int32              `json:"passed_cases"`
	FailedCases    int32              `json:"failed_cases"`
	KeywordHitRate pgtype.Numeric     `json:"keyword_hit_rate"`
	AvgLatencyMs   pgtype.Int4        `json:"avg_latency_ms"`
	AvgTokens      pgtype.Int4        `json:"avg_tokens"`
	ReportMarkdown pgtype.Text        `json:"report_markdown"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RetrievedChunk struct {
	ID              int64          `json:"id"`
	TraceID         string         `json:"trace_id"`
	ChunkID         pgtype.Int8    `json:"chunk_id"`
	Rank            int32          `json:"rank"`
	Score           pgtype.Numeric `json:"score"`
	ContentSnapshot string         `json:"content_snapshot"`
	DocumentName    string         `json:"document_name"`
}

type Trace struct {
	ID               int64              `json:"id"`
	TraceID          string             `json:"trace_id"`
	Question         string             `json:"question"`
	RewrittenQuery   pgtype.Text        `json:"rewritten_query"`
	FinalPrompt      pgtype.Text        `json:"final_prompt"`
	Answer           pgtype.Text        `json:"answer"`
	ModelName        pgtype.Text        `json:"model_name"`
	ConfigSnapshot   []byte             `json:"config_snapshot"`
	LatencyMs        pgtype.Int4        `json:"latency_ms"`
	PromptTokens     pgtype.Int4        `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4        `json:"completion_tokens"`
	TotalTokens      pgtype.Int4        `json:"total_tokens"`
	Status           string             `json:"status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TraceStep struct {
	ID           int64              `json:"id"`
	TraceID      string             `json:"trace_id"`
	StepName     string             `json:"step_name"`
	StepOrder    int32              `json:"step_order"`
	InputData    []byte             `json:"input_data"`
	OutputData   []byte             `json:"output_data"`
	LatencyMs    pgtype.Int4        `json:"latency_ms"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
