// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateRetrievedChunk(ctx context.Context, arg CreateRetrievedChunkParams) (RetrievedChunk, error)
	CreateTrace(ctx context.Context, arg CreateTraceParams) (Trace, error)
	CreateTraceStep(ctx context.Context, arg CreateTraceStepParams) (TraceStep, error)
	GetDocument(ctx context.Context, id int64) (Document, error)
	GetTraceByTraceID(ctx context.Context, traceID string) (Trace, error)
	ListChunksByDocument(ctx context.Context, documentID int64) ([]Chunk, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListRetrievedChunksByTraceID(ctx context.Context, traceID string) ([]RetrievedChunk, error)
	ListTraceSteps(ctx context.Context, traceID string) ([]TraceStep, error)
	ListTraces(ctx context.Context, arg ListTracesParams) ([]Trace, error)
	SearchChunks(ctx context.Context, arg SearchChunksParams) ([]SearchChunksRow, error)
	UpdateChunkEmbedding(ctx context.Context, arg UpdateChunkEmbeddingParams) error
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error)
}

var _ Querier = (*Queries)(nil)
