// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traces.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRetrievedChunk = `-- name: CreateRetrievedChunk :one
INSERT INTO retrieved_chunks (
    trace_id,
    chunk_id,
    rank,
    score,
    content_snapshot,
    document_name
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, trace_id, chunk_id, rank, score, content_snapshot, document_name
`

type CreateRetrievedChunkParams struct {
	TraceID         string         `json:"trace_id"`
	ChunkID         pgtype.Int8    `json:"chunk_id"`
	Rank            int32          `json:"rank"`
	Score           pgtype.Numeric `json:"score"`
	ContentSnapshot string         `json:"content_snapshot"`
	DocumentName    string         `json:"document_name"`
}

func (q *Queries) CreateRetrievedChunk(ctx context.Context, arg CreateRetrievedChunkParams) (RetrievedChunk, error) {
	row := q.db.QueryRow(ctx, createRetrievedChunk,
		arg.TraceID,
		arg.ChunkID,
		arg.Rank,
		arg.Score,
		arg.ContentSnapshot,
		arg.DocumentName,
	)
	var i RetrievedChunk
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.ChunkID,
		&i.Rank,
		&i.Score,
		&i.ContentSnapshot,
		&i.DocumentName,
	)
	return i, err
}

const createTrace = `-- name: CreateTrace :one
INSERT INTO traces (
    trace_id,
    question,
    rewritten_query,
    final_prompt,
    answer,
    model_name,
    config_snapshot,
    latency_ms,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    status,
    error_message
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, trace_id, question, rewritten_query, final_prompt, answer, model_name, config_snapshot, latency_ms, prompt_tokens, completion_tokens, total_tokens, status, error_message, created_at
`

type CreateTraceParams struct {
	TraceID          string      `json:"trace_id"`
	Question         string      `json:"question"`
	RewrittenQuery   pgtype.Text `json:"rewritten_query"`
	FinalPrompt      pgtype.Text `json:"final_prompt"`
	Answer           pgtype.Text `json:"answer"`
	ModelName        pgtype.Text `json:"model_name"`
	ConfigSnapshot   []byte      `json:"config_snapshot"`
	LatencyMs        pgtype.Int4 `json:"latency_ms"`
	PromptTokens     pgtype.Int4 `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4 `json:"completion_tokens"`
	TotalTokens      pgtype.Int4 `json:"total_tokens"`
	Status           string      `json:"status"`
	ErrorMessage     pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, createTrace,
		arg.TraceID,
		arg.Question,
		arg.RewrittenQuery,
		arg.FinalPrompt,
		arg.Answer,
		arg.ModelName,
		arg.ConfigSnapshot,
		arg.LatencyMs,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.Status,
		arg.ErrorMessage,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Question,
		&i.RewrittenQuery,
		&i.FinalPrompt,
		&i.Answer,
		&i.ModelName,
		&i.ConfigSnapshot,
		&i.LatencyMs,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createTraceStep = `-- name: CreateTraceStep :one
INSERT INTO trace_steps (
    trace_id,
    step_name,
    step_order,
    input_data,
    output_data,
    latency_ms,
    status,
    error_message
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, trace_id, step_name, step_order, input_data, output_data, latency_ms, status, error_message, created_at
`

type CreateTraceStepParams struct {
	TraceID      string      `json:"trace_id"`
	StepName     string      `json:"step_name"`
	StepOrder    int32       `json:"step_order"`
	InputData    []byte      `json:"input_data"`
	OutputData   []byte      `json:"output_data"`
	LatencyMs    pgtype.Int4 `json:"latency_ms"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateTraceStep(ctx context.Context, arg CreateTraceStepParams) (TraceStep, error) {
	row := q.db.QueryRow(ctx, createTraceStep,
		arg.TraceID,
		arg.StepName,
		arg.StepOrder,
		arg.InputData,
		arg.OutputData,
		arg.LatencyMs,
		arg.Status,
		arg.ErrorMessage,
	)
	var i TraceStep
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.StepName,
		&i.StepOrder,
		&i.InputData,
		&i.OutputData,
		&i.LatencyMs,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getTraceByTraceID = `-- name: GetTraceByTraceID :one
SELECT id, trace_id, question, rewritten_query, final_prompt, answer, model_name, config_snapshot, latency_ms, prompt_tokens, completion_tokens, total_tokens, status, error_message, created_at
FROM traces
WHERE trace_id = $1
`

func (q *Queries) GetTraceByTraceID(ctx context.Context, traceID string) (Trace, error) {
	row := q.db.QueryRow(ctx, getTraceByTraceID, traceID)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Question,
		&i.RewrittenQuery,
		&i.FinalPrompt,
		&i.Answer,
		&i.ModelName,
		&i.ConfigSnapshot,
		&i.LatencyMs,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listRetrievedChunksByTraceID = `-- name: ListRetrievedChunksByTraceID :many
SELECT id, trace_id, chunk_id, rank, score, content_snapshot, document_name
FROM retrieved_chunks
WHERE trace_id = $1
ORDER BY rank ASC
`

func (q *Queries) ListRetrievedChunksByTraceID(ctx context.Context, traceID string) ([]RetrievedChunk, error) {
	rows, err := q.db.Query(ctx, listRetrievedChunksByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievedChunk
	for rows.Next() {
		var i RetrievedChunk
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.ChunkID,
			&i.Rank,
			&i.Score,
			&i.ContentSnapshot,
			&i.DocumentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraceSteps = `-- name: ListTraceSteps :many
SELECT id, trace_id, step_name, step_order, input_data, output_data, latency_ms, status, error_message, created_at
FROM trace_steps
WHERE trace_id = $1
ORDER BY step_order ASC
`

func (q *Queries) ListTraceSteps(ctx context.Context, traceID string) ([]TraceStep, error) {
	rows, err := q.db.Query(ctx, listTraceSteps, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraceStep
	for rows.Next() {
		var i TraceStep
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.StepName,
			&i.StepOrder,
			&i.InputData,
			&i.OutputData,
			&i.LatencyMs,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraces = `-- name: ListTraces :many
SELECT id, trace_id, question, rewritten_query, final_prompt, answer, model_name, config_snapshot, latency_ms, prompt_tokens, completion_tokens, total_tokens, status, error_message, created_at
FROM traces
WHERE ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR question ILIKE '%' || $4::text || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTracesParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Status  pgtype.Text `json:"status"`
	Keyword pgtype.Text `json:"keyword"`
}

func (q *Queries) ListTraces(ctx context.Context, arg ListTracesParams) ([]Trace, error) {
	rows, err := q.db.Query(ctx, listTraces,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trace
	for rows.Next() {
		var i Trace
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Question,
			&i.RewrittenQuery,
			&i.FinalPrompt,
			&i.Answer,
			&i.ModelName,
			&i.ConfigSnapshot,
			&i.LatencyMs,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
